rgname                 = "stage-lamiae-rg"
service_principal_name = "stage-lamiae-spn"
keyvault_name          = "stage-lamiae-kv-101"
SUB_ID = "becc6b61-adfd-477e-abfe-6bd6a1973f49"
cluster_name = "stage-lamiae-cluster"
node_pool_name = "stage-lamiae-np"