rgname                 = "dev-lamiae-rg"
service_principal_name = "dev-lamiae-spn"
keyvault_name          = "dev-lamiae-kv-101"
SUB_ID = "becc6b61-adfd-477e-abfe-6bd6a1973f49"
cluster_name = "dev-lamiae-cluster"
node_pool_name = "dev-lamiae-np"
